apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse
  name: redis
  namespace: discourse
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    deploymentconfig: redis
  sessionAffinity: None
  type: ClusterIP
