apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: postgresql
  namespace: discourse
  labels:
    app: postgresql
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker.io/centos/postgresql-10-centos7:latest
    name: stable
    referencePolicy:
      type: Local
